### ISSUE TITLE
Problem with jest

### ISSUE THREAD

**Issue by heniotierra** [TiagoDanin/Require-From-Web#14]
I run into the error below when using this lib inside jest:

```
      TypeError: _module._compile is not a function
          at module.exports (/home/henio/Projetos/zrp/api-web-zrp/node_modules/require-from-web/index.js:20:10)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
          at Object.<anonymous> (/home/henio/Projetos/zrp/api-web-zrp/src/gateway/tests/handler.test.js:29:17)
```

**Comment by findingorder** [comment]
I also get this error.  It looks like it's source is index.js, line 20.

**Comment by TiagoDanin** [comment]
No problems here, could send step by step?

**Comment by heniotierra** [comment]
I'm no longer working on that project, sorry.

Em qui., 30 de abr. de 2020 às 22:55, Tiago Danin <notifications@github.com>
escreveu:

**Comment by TiagoDanin** [comment]
ok 👍
